#!/bin/bash

set -euo pipefail

ln -fs ie.macinnes.tvheadend-release.apk app/build/outputs/apk/ie.macinnes.tvheadend_${CI_COMMIT_TAG}.apk

echo " --> Uploading ie.macinnes.tvheadend_${CI_COMMIT_TAG}.apk"
FILE_LINK=$(curl --silent --request POST --header "PRIVATE-TOKEN: ${CI_JOB_TOKEN}" --form "file=@app/build/outputs/apk/ie.macinnes.tvheadend_${CI_COMMIT_TAG}.apk" https://gitlab.macinnes.ie/api/v3/projects/${CI_PROJECT_ID}/uploads | jq -r '.markdown')

echo " --> Generating Release Notes"
DESCRIPTION=$(./tools/generate-changelog)
DESCRIPTION+="<br><br>Download: ${FILE_LINK}"

echo " --> Creating release ${CI_COMMIT_TAG}"
curl --silent --request POST --header "PRIVATE-TOKEN: ${CI_JOB_TOKEN}" -F "description=${DESCRIPTION}" https://gitlab.macinnes.ie/api/v3/projects/${CI_PROJECT_ID}/repository/tags/${CI_COMMIT_TAG}/release > /dev/null
RESULT=$?

if [ $RESULT -eq 0 ]; then
  echo " --> Release already exists, updating release ${CI_COMMIT_TAG}"
  curl --silent --request PUT --header "PRIVATE-TOKEN: ${CI_JOB_TOKEN}" -F "description=${DESCRIPTION}" https://gitlab.macinnes.ie/api/v3/projects/${CI_PROJECT_ID}/repository/tags/${CI_COMMIT_TAG}/release > /dev/null
fi

echo " --> Done"
